import { Document, Page, Text, View, StyleSheet, renderToStream, Font } from '@react-pdf/renderer'
import { Student, ClearanceRequest, StageStatus } from '@prisma/client'

// Create styles
const styles = StyleSheet.create({
  page: {
    padding: 50,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 40,
    textAlign: 'center',
    borderBottom: '2 solid #000',
    paddingBottom: 20,
  },
  university: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#1a365d',
  },
  department: {
    fontSize: 16,
    color: '#4a5568',
    marginBottom: 5,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 40,
    textTransform: 'uppercase',
  },
  detailsContainer: {
    marginBottom: 40,
    padding: 20,
    backgroundColor: '#f7fafc',
    borderRadius: 8,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 15,
  },
  label: {
    width: 150,
    fontSize: 12,
    fontWeight: 'bold',
    color: '#4a5568',
  },
  value: {
    flex: 1,
    fontSize: 14,
    fontWeight: 'bold',
  },
  signatureContainer: {
    marginTop: 60,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  signatureBlock: {
    width: 200,
    textAlign: 'center',
  },
  signatureLine: {
    borderTop: '1 solid #000',
    marginTop: 40,
    paddingTop: 10,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 50,
    right: 50,
    textAlign: 'center',
    fontSize: 10,
    color: '#a0aec0',
    borderTop: '1 solid #e2e8f0',
    paddingTop: 10,
  }
})

export async function generateCertificatePDF(
  student: Student,
  request: ClearanceRequest & { stages: any[] }
) {
  const clearanceDate = request.updatedAt.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  })

  // Ensure all stages were approved
  const allApproved = request.stages.length === 5 && request.stages.every(s => s.status === StageStatus.APPROVED)
  
  if (!allApproved) {
    throw new Error('Cannot generate certificate: Clearance is not fully approved.')
  }

  const MyDocument = () => (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.university}>Lead City University, Ibadan</Text>
          <Text style={styles.department}>Department of Computer Science</Text>
        </View>

        <Text style={styles.title}>Final Clearance Certificate</Text>

        <View style={styles.detailsContainer}>
          <View style={styles.row}>
            <Text style={styles.label}>Student Name:</Text>
            <Text style={styles.value}>{student.fullName.toUpperCase()}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Matriculation Number:</Text>
            <Text style={styles.value}>{student.matricNumber}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Programme:</Text>
            <Text style={styles.value}>{student.programme}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Faculty:</Text>
            <Text style={styles.value}>{student.faculty}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Clearance Date:</Text>
            <Text style={styles.value}>{clearanceDate}</Text>
          </View>
        </View>

        <Text style={{ fontSize: 12, lineHeight: 1.5, marginBottom: 40 }}>
          This is to certify that the above-named student has successfully completed the graduation clearance process 
          across all required administrative units (Library, Bursary, Department, Faculty, and Registry). 
          They are hereby cleared of all obligations to the university.
        </Text>

        <View style={styles.signatureContainer}>
          <View style={styles.signatureBlock}>
            <Text style={styles.signatureLine}>Date</Text>
          </View>
          <View style={styles.signatureBlock}>
            <Text style={{ fontStyle: 'italic', marginBottom: 10 }}>Electronically Signed</Text>
            <Text style={styles.signatureLine}>Registry Officer</Text>
          </View>
        </View>

        <Text style={styles.footer}>
          This document was electronically generated by the LCU Online Student Clearance System. 
          Reference ID: {request.id}
        </Text>
      </Page>
    </Document>
  )

  const stream = await renderToStream(<MyDocument />)
  return stream
}
